name: Django Tests with Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Add PostgreSQL/MySQL here if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change if using another version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django

    - name: Run tests with pytest
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings  # Replace with your Django settings module
      run: |
        python manage.py migrate
        pytest